# Generated by Django 5.1 on 2024-08-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiseaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocassion',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('art', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='oiseaux.art')),
            ],
        ),
    ]
