# Generated by Django 5.1 on 2024-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiseaux', '0002_ocassion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('ocassion', models.ManyToManyField(to='oiseaux.ocassion')),
            ],
        ),
    ]
