# Generated by Django 5.1 on 2024-08-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiseaux', '0004_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='name',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='oiseaux.registry')),
            ],
        ),
    ]
