# Generated by Django 5.1 on 2024-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiseaux', '0006_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='val', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registry',
            name='registry_link',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
