# Generated by Django 5.1 on 2024-08-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oiseaux', '0007_person_last_name_alter_registry_registry_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocassion',
            old_name='name',
            new_name='title',
        ),
    ]
