# Generated by Django 5.1 on 2024-08-12 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiseaux', '0008_rename_name_ocassion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='registry_link',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Your link should just contain letters, numbers or _.')]),
        ),
    ]
