# Generated by Django 5.1 on 2024-08-12 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiseaux', '0009_alter_registry_registry_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='photo',
        ),
        migrations.AddField(
            model_name='registry',
            name='photo_url',
            field=models.CharField(default=1, max_length=250, validators=[django.core.validators.RegexValidator('^.*\\.(jpg|JPG|jpeg|PNG|png)$', 'Your file has to be jpg or png.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registry',
            name='registry_link',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Your link should just contain letters, numbers or underscore.')]),
        ),
    ]
